Реализация популярных функций потерь на PyTorch и NumPy

- L1Loss
- MSELoss
- CrossEntropyLoss
- NLLLoss
- BCELoss
- BCEWithLogitsLoss
- MarginRankingLoss
- SmoothL1Loss

In [1]:
import numpy as np

import torch
import torch.nn as nn

In [2]:
np.__version__

'1.16.5'

In [3]:
torch.__version__

'1.3.1'

### L1Loss

In [4]:
y_pred = torch.randn(2,3)
y_true = torch.randn(2,3)

print(f"y_pred:\n{y_pred}")
print(f"y_true:\n{y_true}")

y_pred:
tensor([[-0.5336, -0.4907,  0.2312],
        [-0.1624,  2.0201,  2.2566]])
y_true:
tensor([[ 0.4239, -0.8511, -1.6998],
        [-0.9975, -0.1470,  0.7654]])


In [5]:
# PyTorch

torch_loss = nn.L1Loss()(y_pred, y_true)

print(f"PyTorch loss: {torch_loss}")

PyTorch loss: 1.2903779745101929


In [6]:
# NumPy

np_loss = np.abs(y_pred.numpy() - y_true.numpy()).mean()

print(f"PyTorch loss: {np_loss}")

PyTorch loss: 1.2903779745101929


### MSELoss

In [7]:
y_pred = torch.randn(2, 3)
y_true = torch.randn(2, 3)

print(f"y_pred:\n{y_pred}")
print(f"y_true:\n{y_true}")

y_pred:
tensor([[ 0.0861, -0.1074, -0.3204],
        [-1.7932,  0.5214, -0.2649]])
y_true:
tensor([[ 0.0359,  0.5286,  0.3880],
        [ 1.2208,  0.1837, -1.7642]])


In [8]:
# PyTorch

torch_loss = nn.MSELoss()(y_pred, y_true)

print(f"PyTorch loss: {torch_loss}")

PyTorch loss: 2.0592100620269775


In [9]:
# NumPy

np_loss = ((y_pred.numpy() - y_true.numpy())**2).mean()

print(f"PyTorch loss: {np_loss}")

PyTorch loss: 2.0592100620269775


### CrossEntropyLoss

In [10]:
x = torch.randn(2, 4)
y = torch.LongTensor(2).random_(4)

print(f"x:\n{x}")
print(f"y:\n{y}")

x:
tensor([[-0.3035, -0.8180, -1.9438,  0.6326],
        [-2.8267, -0.7586, -0.4638,  0.7497]])
y:
tensor([2, 3])


In [11]:
# PyTorch

torch_loss = nn.CrossEntropyLoss()(x, y)

print(f"PyTorch loss: {torch_loss}")

PyTorch loss: 1.7722333669662476


In [12]:
# NumPy

if isinstance(x, torch.Tensor):
    x = x.numpy()
if isinstance(y, torch.Tensor):
    y = y.numpy()

arr = []
for k in range(len(x)):
    arr.append(-np.log(np.exp(x[k][y[k]]) / np.exp(x[k]).sum()))

print(f"PyTorch loss: {np.mean(arr)}")

PyTorch loss: 1.772233486175537


### NLLLoss

In [13]:
x_ = torch.randn(3, 4)
x = nn.LogSoftmax(dim=1)(x_)

y = torch.LongTensor(3).random_(4)

print(f"x:\n{x}")
print(f"y:\n{y}")

x:
tensor([[-0.7438, -3.4877, -2.3233, -0.9260],
        [-0.4407, -2.4457, -1.8125, -2.2395],
        [-1.3698, -0.6933, -2.2964, -1.9292]])
y:
tensor([1, 1, 3])


In [14]:
# PyTorch

torch_loss = nn.NLLLoss()(x, y)

print(f"PyTorch loss: {torch_loss}")

PyTorch loss: 2.6208689212799072


In [15]:
# NumPy

arr = []
for k in range(len(x)):
    arr.append(-x[k][y[k]])
    
np_loss = np.mean(arr)    
print(f"PyTorch loss: {np_loss}")

PyTorch loss: 2.6208689212799072


### BCELoss

In [16]:
x = torch.rand(3, 4)

y = torch.empty(x.size()).random_(2)

print(f"x:\n{x}")
print(f"y:\n{y}")

x:
tensor([[0.8322, 0.2102, 0.4196, 0.1992],
        [0.6541, 0.7871, 0.9964, 0.0181],
        [0.2712, 0.8633, 0.6485, 0.2386]])
y:
tensor([[0., 1., 1., 1.],
        [1., 1., 0., 1.],
        [0., 0., 0., 0.]])


In [17]:
# PyTorch

torch_loss = nn.BCELoss()(x, y)

print(f"PyTorch loss: {torch_loss}")

PyTorch loss: 1.6466469764709473


In [18]:
# NumPy

if isinstance(x, torch.Tensor):
    x = x.numpy()
if isinstance(y, torch.Tensor):
    y = y.numpy()

arr = []
for i in range(len(x)):
    iarr = []
    for j in range(len(x[i])):
        iarr.append(-np.log(x[i][j]) if y[i][j]==1 else -np.log(1-x[i][j]))
    arr.append(iarr)
torch_loss = np.mean(arr)

print(f"PyTorch loss: {torch_loss}")

PyTorch loss: 1.6466470747390496


### BCEWithLogitsLoss

In [19]:
x = torch.rand(3, 4)
y = torch.FloatTensor(x.size()).random_(2)

print(f"x:\n{x}")
print(f"y:\n{y}")

x:
tensor([[0.5384, 0.5518, 0.0852, 0.2603],
        [0.9861, 0.0202, 0.4962, 0.1364],
        [0.8371, 0.7375, 0.2028, 0.5724]])
y:
tensor([[0., 0., 0., 1.],
        [1., 0., 1., 1.],
        [0., 0., 1., 0.]])


In [20]:
# PyTorch

torch_loss = nn.BCEWithLogitsLoss()(x, y)

print(f"PyTorch loss: {torch_loss}")

PyTorch loss: 0.7814812064170837


In [21]:
# NumPy

if isinstance(x, torch.Tensor):
    x = x.numpy()
    # just apply sigmoid
    x = 1/(1 + np.exp(-x)) 
if isinstance(y, torch.Tensor):
    y = y.numpy()

arr = []
for i in range(len(x)):
    iarr = []
    for j in range(len(x[i])):
        iarr.append(-np.log(x[i][j]) if y[i][j]==1 else -np.log(1-x[i][j]))
    arr.append(iarr)
torch_loss = np.mean(arr)

print(f"PyTorch loss: {torch_loss}")

PyTorch loss: 0.7814811944753589


### MarginRankingLoss

In [22]:
x1 = torch.randn(3)
x2 = torch.randn(3)
y = torch.FloatTensor(np.random.choice([1, -1], 3))

print(f"x1:\n{x1}")
print(f"x2:\n{x2}")
print(f"y:\n{y}")

x1:
tensor([ 0.4836,  0.6102, -0.5548])
x2:
tensor([-0.1121,  0.7968, -1.0851])
y:
tensor([1., 1., 1.])


In [23]:
# PyTorch

torch_loss = nn.MarginRankingLoss(margin=0.1)(x1, x2, y)

print(f"PyTorch loss: {torch_loss}")

PyTorch loss: 0.09553644061088562


In [24]:
# NumPy

margin=0.1

if isinstance(x1, torch.Tensor):
    x1 = x1.numpy()
if isinstance(x2 , torch.Tensor):
    x2 = x2.numpy()
if isinstance(y, torch.Tensor):
    y = y.numpy()
    
arr = []
for i in range(len(x1)):
    arr.append(max(0, -y[i]*(x1[i]-x2[i]) + margin))
    
torch_loss = np.mean(arr)

print(f"PyTorch loss: {torch_loss}")

PyTorch loss: 0.0955364425977071


### SmoothL1Loss

In [25]:
x = torch.randn(2, 3)
y = torch.randn(2, 3)

print(f"x:\n{x}")
print(f"y:\n{y}")

x:
tensor([[-0.9299, -0.6225,  1.5061],
        [ 0.3645,  0.0165,  0.8457]])
y:
tensor([[ 0.6433, -0.3175, -1.6047],
        [ 1.3342, -0.0448, -1.0458]])


In [26]:
# PyTorch

torch_loss = nn.SmoothL1Loss()(x, y)

print(f"PyTorch loss: {torch_loss}")

PyTorch loss: 0.9323527216911316


In [27]:
# NumPy

def smoothl1loss(x, y):
    if abs(x-y) < 1: return 1 / 2 * (x - y)**2
    else: return abs(x-y) -1 / 2

if isinstance(x, torch.Tensor):
    x = x.numpy()
if isinstance(y, torch.Tensor):
    y = y.numpy()

arr = []
for i in range(len(x)):
    iarr=[]
    for j in range(len(x[i])):
        iarr.append(smoothl1loss(x[i][j], y[i][j]))
    arr.append(iarr)
    
torch_loss = np.mean(arr)

print(f"PyTorch loss: {torch_loss}")

PyTorch loss: 0.932352750377305
